# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AtheNAC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rAtheNAC.proto\x12\x11PIXIS.Grpc.Protos\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x03\n\x11HostReportRequest\x12\x11\n\thost_name\x18\x01 \x01(\t\x12\x0c\n\x04MACs\x18\x02 \x03(\t\x12\x13\n\x0b\x64omain_name\x18\x03 \x01(\t\x12;\n\x0blogon_users\x18\x04 \x03(\x0b\x32&.PIXIS.Grpc.Protos.HostReportLogonUser\x12\x0f\n\x07os_type\x18\x05 \x01(\t\x12\x0f\n\x07os_desc\x18\x06 \x01(\t\x12\x14\n\x0cshare_folder\x18\x07 \x03(\t\x12\x17\n\x0fpending_hot_fix\x18\x08 \x03(\t\x12\x43\n\x1fwindows_hot_fix_last_check_time\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13local_admin_account\x18\n \x03(\t\x12-\n\ttimestamp\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x19motherboard_serial_number\x18\x0c \x01(\t\x12.\n\tsoftwares\x18\r \x03(\x0b\x32\x1b.PIXIS.Grpc.Protos.Software\x12\x36\n\x12\x41gentLastCheckTime\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"V\n\x13HostReportLogonUser\x12\x15\n\rlogon_account\x18\x01 \x01(\t\x12\x14\n\x0cremote_login\x18\x02 \x01(\x08\x12\x12\n\ngpo_result\x18\x03 \x01(\t\"v\n\x08Software\x12\x13\n\x0b\x44isplayName\x18\x01 \x01(\t\x12\x16\n\x0e\x44isplayVersion\x18\x02 \x01(\t\x12\x11\n\tPublisher\x18\x03 \x01(\t\x12\x13\n\x0bInstallDate\x18\x04 \x01(\t\x12\x15\n\rEstimatedSize\x18\x05 \x01(\t\"\"\n\x0fHostReportReply\x12\x0f\n\x07Message\x18\x01 \x01(\t2p\n\x10HostAgentService\x12\\\n\x0eSendHostReport\x12$.PIXIS.Grpc.Protos.HostReportRequest\x1a\".PIXIS.Grpc.Protos.HostReportReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AtheNAC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOSTREPORTREQUEST._serialized_start=70
  _HOSTREPORTREQUEST._serialized_end=569
  _HOSTREPORTLOGONUSER._serialized_start=571
  _HOSTREPORTLOGONUSER._serialized_end=657
  _SOFTWARE._serialized_start=659
  _SOFTWARE._serialized_end=777
  _HOSTREPORTREPLY._serialized_start=779
  _HOSTREPORTREPLY._serialized_end=813
  _HOSTAGENTSERVICE._serialized_start=815
  _HOSTAGENTSERVICE._serialized_end=927
# @@protoc_insertion_point(module_scope)
